### ISSUE TITLE
Nestjs wrapper throws `TypeError: Cannot read property 'forEach' of undefined` when the root module don't have controllers

### ISSUE THREAD

**Issue by micalevisk** [infinite-cat/recap.dev-client#12]
With the following setup:

```typescript
@Module({
  controllers: [AppController],
  providers: [AppService],
})
class FooModule {}

@Module({
  imports: [ConfigModule.forRoot(), FooModule],
})
export class AppModule {}
```

`Reflect.getMetadata('controllers', module)` will return `undefined` thus the line below will throw `TypeError: Cannot read property 'forEach' of undefined`

https://github.com/infinite-cat/recap.dev-client/blob/7c5210fc2b5907022f1211ee34dd61f6ed820c6d/src/wrappers/nestjs.ts#L11-L12

The stack trace I've got:

```
(node:392574) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'forEach' of undefined
    at Object.wrapNestJsModule (x/node_modules/@recap.dev/client/dist/client.umd.js:25987:51)
    at bootstrap (x/dist/main.js:13:58)
    at Object.<anonymous> (x/dist/main.js:27:1)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
```

**Comment by ArsenyYankovsky** [comment]
Thanks for reporting it! I'll fix it right away.

**Comment by ArsenyYankovsky** [comment]
@micalevisk 
New 1.12.2 version of the `@recap.dev/client` with a fix was just released. Please let me know if I can close the ticket.

**Comment by ArsenyYankovsky** [comment]
You want to wrap your `FooModule` in `wrapNestJsModule`. Read more [here](https://recap.dev/docs/tracing/nestjs-application#setting-up-a-basic-tracing)

**Comment by micalevisk** [comment]
So for each module that have controllers I need to call `wrapNestJsModule` instead of just calling for the root/entry module, right? I understand this after reading the source code. IMO the docs didn't make this clear. Thank you!

**Comment by ArsenyYankovsky** [comment]
@micalevisk Exactly, the motivation is that you might want to trace only specific modules. Let me know if you'd like a flag to introspect imported modules.

**Comment by micalevisk** [comment]
My modules are generally organized like this:

<img src="https://user-images.githubusercontent.com/13461315/106671356-bfa0b180-6584-11eb-9994-25336d1a5882.png" width="500" height="300" />

so I don't think that instrospection is necessary.
