### ISSUE TITLE
Nestjs wrapper throws `TypeError: Cannot convert undefined or null to object` error when Nest providers are plain objects

### ISSUE THREAD

**Issue by micalevisk** [infinite-cat/recap.dev-client#14]
Hi!

When using the short-hand syntax of [standard providers](https://docs.nestjs.com/fundamentals/custom-providers#standard-providers) like `providers: [CatsService]` everything works fine, but this is the same as writting:

```typescript
providers: [
  {
    provide: CatsService,
    useClass: CatsService,
  }
]
```
so I think that `wrapNestJsModule` should handle this as well.

```typescript
// or, for real world scenarios
providers: [
  {
    provide: APP_PIPE,
    useClass: ValidationPipe,
  }
]
```

This is not currently supported because the `injectable` object below will be this `{ provide:..., useClass:... }` instead of the value of `useClass` property

https://github.com/infinite-cat/recap.dev-client/blob/fc3b79d2099e6e1d4d13010bb5fe438e5ede7636/src/wrappers/nestjs.ts#L16-L18

which leads to `TypeError: Cannot convert undefined or null to object` error here in L53 due to `Object.getOwnPropertyNames(undefined)`

https://github.com/infinite-cat/recap.dev-client/blob/fc3b79d2099e6e1d4d13010bb5fe438e5ede7636/src/wrappers/common.ts#L51-L53

Maybe you can resolve the value of `injectable` in the same way that Nest's core do, somehow.

---

Note that even if recap.dev supports the usage of Nestjs [custom providers](https://docs.nestjs.com/fundamentals/custom-providers) via `useClass`, there will still be a need to deal with [non-class-based provider tokens](https://docs.nestjs.com/fundamentals/custom-providers#non-class-based-provider-tokens) since they will be returned by `Reflect.getMetadata('providers', module)` and thus the `TypeError` will be thrown again :confused:

**Comment by ArsenyYankovsky** [comment]
@micalevisk Sorry I don't have time to look at it today, but will do tomorrow.

**Comment by micalevisk** [comment]
Also, if you'll change `wrapNestJsModule`, I suggest to replace `any` ([L11](https://github.com/infinite-cat/recap.dev-client/blob/fc3b79d2099e6e1d4d13010bb5fe438e5ede7636/src/wrappers/nestjs.ts#L11)) by using generics to make this less loose, like

```diff
- export const wrapNestJsModule = (module: any) => { 
+ export const wrapNestJsModule = <Module>(module: Module) => {
```

https://github.com/infinite-cat/recap.dev-client/blob/fc3b79d2099e6e1d4d13010bb5fe438e5ede7636/src/wrappers/nestjs.ts#L11

**Comment by ArsenyYankovsky** [comment]
@micalevisk Please try with the new 1.12.3 version. It should handle custom providers and non-class providers alike.

**Comment by micalevisk** [comment]
It do works now! thank you.

But I think that you could improve the unit names. I didn't understand why you choose using `injectable.provide` as `className` instead keeping using `useClass.name`, since with that I'll loose the information about the provider that was reached

https://github.com/infinite-cat/recap.dev-client/blob/bc32d6836559be45a4a44c3cfadf67403b97e49e/src/wrappers/nestjs.ts#L14-L17

I think

![eg](https://user-images.githubusercontent.com/13461315/106953213-7e390f00-6708-11eb-9847-da1a36a337b9.png)

should display `ClassSerializerInterceptor.intercept` instead, when I set up this:

```typescript
providers: [
  {
    provide: APP_INTERCEPTOR, // `injectable.provide` will always receive `'APP_INTERCEPTOR'`
    useClass: ClassSerializerInterceptor,
  }
]
```

and also I could have as many provider with the token `APP_FILTER` as I needed, thus all of them will be identified by the same unit name :confused:

**Comment by ArsenyYankovsky** [comment]
@micalevisk 
I thought it's better to use the 'injectable.provide' name since you might use the same class for different providers. I can see how knowing the exact class name could also be benefitial.
